#PATH to all data
data_dir: PATH_TO_ALL_DATA

#Connecting to a database
adapter: mysql2
host: localhost
database: db_name
user: database_username
password: database_password

# Extract data from models:
mapped:
  tables:
  - :example_table_name
  - :example_table_name_two
  - :example_table_name_three

## MAPPING ##
mapping_dir: example_data/mapping.json
contentful_structure_dir: example_data/contentful_structure.json

## CONVERT
content_model_json: example_data/contentful_model.json
converted_model_dir: example_data/contentful_structure.json
