#PATH to all data
data_dir: PATH_TO_ALL_DATA

#Connecting to a database
adapter: mysql2
host: localhost
database: database_name
user: username
password: password

# Extract data from models:
mapped:
  tables:
  - :table_name
  - :table_name_2

## MAPPING ##
mapping_dir: PATH_TO_FILE/mapping.json
contentful_structure_dir: PATH_TO_FILE/contentful_structure.json

## CONVERT
content_model_json: PATH_TO_FILE/contentful_model.json
import_form_dir: PATH_TO_FILE/contentful_structure.json
